(()=>{
'use strict';
const $=s=>document.querySelector(s);
const canvas=$('#previewCanvas'),ctx=canvas?.getContext('2d',{willReadFrequently:true});
let img=null,imgFile=null,imgData=null,lastAnalysis=null,aircraftDetection=null,detectedReg='',regRun=0,regCancelled=false,ocrWorker=null;
const css=document.createElement('style');css.textContent=`
.preview-wrap{position:relative!important;display:block!important;overflow:auto!important;line-height:0!important;background:#eef3f8!important}.preview-wrap canvas{display:block!important}.preview-wrap #previewCanvas{position:relative!important;z-index:1!important;max-width:none!important}.preview-wrap #overlayCanvas{position:absolute!important;left:0!important;top:0!important;z-index:5!important;pointer-events:none!important}.reg-search-overlay{position:absolute;z-index:6;pointer-events:none;border:2px solid #0878d1;border-radius:8px;box-shadow:0 0 0 9999px rgba(8,120,209,.04)}.technical-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.technical-item{transition:.2s;box-shadow:0 3px 10px rgba(28,55,85,.04)}.technical-item b{font-size:12px}.technical-item span{font-size:11px}.aircraft-state.detected{box-shadow:inset 4px 0 0 var(--good)}.aircraft-state.none{box-shadow:inset 4px 0 0 var(--bad)}.source-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px;background:#94a3b8}.source-dot.ok{background:#079669;box-shadow:0 0 0 3px #07966920}.source-dot.wait{background:#c98500;box-shadow:0 0 0 3px #c9850020}.source-dot.no{background:#dc3d5b;box-shadow:0 0 0 3px #dc3d5b20}.reg-target{margin-top:10px;padding:10px 12px;border:1px solid #cfe0ef;border-radius:11px;background:linear-gradient(135deg,#f5fbff,#fff);font-size:11px;color:#52657a}.reg-target b{color:#0878d1}.reg-target strong{display:block;margin-top:3px;color:#122033}.ocr-status{display:flex;align-items:center;gap:8px}.spinner{width:12px;height:12px;border:2px solid #cfe0ef;border-top-color:#0878d1;border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
@media(max-width:650px){.technical-grid{grid-template-columns:1fr}.reg-target{font-size:10px}}
`;document.head.appendChild(css);
const progress=(p,msg,phase='TECHNICAL')=>{const f=$('#analysisFill'),l=$('#analysisProgressLabel'),ph=$('#analysisProgress')?.querySelector('.progress-top span:last-child');if(f)f.style.width=Math.max(0,Math.min(100,p))+'%';if(l)l.textContent=`${msg} • ${Math.round(p)}%`;if(ph)ph.textContent=phase};
const regProgress=(p,msg)=>{const f=$('#registrationFill'),l=$('#registrationProgressLabel'),n=$('#registrationPercent');if(f)f.style.width=p+'%';if(l)l.textContent=msg;if(n)n.textContent=Math.round(p)+'%'};
function lum(p,i){return .2126*p[i]+.7152*p[i+1]+.0722*p[i+2]}
function region(p,w,h,x0,y0,x1,y1,step=5){x0=Math.max(0,Math.floor(x0));y0=Math.max(0,Math.floor(y0));x1=Math.min(w,Math.ceil(x1));y1=Math.min(h,Math.ceil(y1));let s=0,n=0;for(let y=y0;y<y1;y+=step)for(let x=x0;x<x1;x+=step){s+=lum(p,(y*w+x)*4);n++}return n?s/n:0}
function backlight(d,bbox){const{width:w,height:h,data:p}=d;if(!bbox)return{risk:0,level:'unknown',brightest:'unknown',aircraft:0,front:0,rear:0,top:0,bottom:0,message:'Aircraft area is required for directional backlight analysis.'};let[x,y,bw,bh]=bbox; x=Math.max(0,x);y=Math.max(0,y);bw=Math.min(w-x,bw);bh=Math.min(h-y,bh);const pad=Math.max(4,Math.min(w,h)*.018),air=region(p,w,h,x,y,x+bw,y+bh,Math.max(3,Math.round(Math.min(w,h)/500)));const zones={front:region(p,w,h,x-pad,y+bh*.2,x,y+bh*.8),rear:region(p,w,h,x+bw,y+bh*.2,x+bw+pad,y+bh*.8),top:region(p,w,h,x+bw*.2,y-pad,x+bw*.8,y),bottom:region(p,w,h,x+bw*.2,y+bh,x+bw*.8,y+bh+pad)};const bright=Object.entries(zones).sort((a,b)=>b[1]-a[1])[0];const delta=Math.max(0,bright[1]-air);const risk=Math.min(100,Math.round(delta*1.7+(air<95?18:0)+(bright[1]>185?18:0)));const level=risk>=65?'high':risk>=35?'moderate':'low';const names={front:'front',rear:'behind',top:'top',bottom:'below'};return{risk,level,brightest:names[bright[0]],aircraft:air,front:zones.front,rear:zones.rear,top:zones.top,bottom:zones.bottom,message:level==='high'?`Strong directional backlight: the ${names[bright[0]]} side is much brighter than the aircraft.`:level==='moderate'?`Possible backlight from the ${names[bright[0]]} side.`:'No strong directional backlight detected around the aircraft.'}}
function analyse(d,bbox){const{width:w,height:h,data:p}=d,n=w*h;let sum=0,s2=0,hi=0,lo=0,hist=Array(256).fill(0);const step=n>5000000?2:1;for(let i=0;i<n;i+=step){const y=lum(p,i*4);sum+=y;s2+=y*y;hist[Math.round(y)]++;if(y>=250)hi++;if(y<=5)lo++}const samples=Math.ceil(n/step),mean=sum/samples,sd=Math.sqrt(Math.max(0,s2/samples-mean*mean)),clip=(hi+lo)/samples,resolution=w>=3000&&h>=2000?'excellent':w>=2000&&h>=1300?'good':w>=1600&&h>=1000?'borderline':'low',exposure=mean<75?'dark':mean>190?'bright':hi/samples>.012||lo/samples>.08?'high-contrast':'good',noise=sd>68?'high':sd>48?'moderate':'low',back=backlight(d,bbox);let score=(resolution==='excellent'?25:resolution==='good'?22:resolution==='borderline'?15:7)+(exposure==='good'?20:exposure==='high-contrast'?14:10)+(noise==='low'?15:noise==='moderate'?10:5)+(clip<.035?15:clip<.07?9:4)+20-(back.risk>=65?15:back.risk>=35?7:0);return{mean,clip,resolution,exposure,noise,hist,score:Math.max(0,Math.min(100,Math.round(score))),back}}
function drawHistogram(a){const c=$('#histogram'),g=c?.getContext('2d');if(!c||!g)return;g.clearRect(0,0,c.width,c.height);const m=Math.max(...a.hist,1);g.beginPath();a.hist.forEach((v,i)=>{const x=i/255*c.width,y=c.height-v/m*(c.height-10);i?g.lineTo(x,y):g.moveTo(x,y)});g.strokeStyle='#0878d1';g.lineWidth=1.7;g.stroke();g.strokeStyle='#cbd5e1';g.lineWidth=1;[.25,.5,.75].forEach(x=>{g.beginPath();g.moveTo(c.width*x,0);g.lineTo(c.width*x,c.height);g.stroke()})}
function horizon(){if(!imgData)return .5;const{width:w,height:h,data:p}=imgData;let best=.5,bs=-1;for(let y=h*.2;y<h*.85;y+=Math.max(5,h/100)){let s=0,n=0;for(let x=0;x<w;x+=12){const i=(Math.floor(y)*w+x)*4;s+=Math.abs(lum(p,Math.max(0,i-w*4))-lum(p,Math.min(p.length-4,i+w*4)));n++}const v=s/n;if(v>bs){bs=v;best=y/h}}return best}
function dust(){if(!imgData)return[];const{width:w,height:h,data:p}=imgData,pts=[],step=Math.max(14,Math.floor(Math.min(w,h)/100));for(let y=step*2;y<h-step*2;y+=step)for(let x=step*2;x<w-step*2;x+=step){const v=lum(p,(y*w+x)*4);let s=0,n=0,r=Math.max(5,Math.floor(step/2));for(let yy=-r;yy<=r;yy+=Math.max(2,Math.floor(r/2)))for(let xx=-r;xx<=r;xx+=Math.max(2,Math.floor(r/2))){s+=lum(p,(Math.max(0,Math.min(h-1,y+yy))*w+Math.max(0,Math.min(w-1,x+xx)))*4);n++}if(s/n-v>32)pts.push({x:x/w,y:y/h});if(pts.length>=16)return pts}return pts}
function drawOverlays(){const oc=$('#overlayCanvas');if(!oc||!canvas?.width)return;const w=canvas.clientWidth,h=canvas.clientHeight;oc.width=Math.max(1,w);oc.height=Math.max(1,h);oc.style.width=w+'px';oc.style.height=h+'px';const g=oc.getContext('2d');g.clearRect(0,0,w,h);if($('#overlayCenter')?.checked){g.strokeStyle='rgba(8,120,209,.85)';g.lineWidth=1.5;g.beginPath();g.moveTo(w/2,0);g.lineTo(w/2,h);g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke()}if($('#overlayGrid')?.checked){g.strokeStyle='rgba(8,120,209,.32)';g.lineWidth=1;g.beginPath();for(let i=1;i<3;i++){g.moveTo(w*i/3,0);g.lineTo(w*i/3,h);g.moveTo(0,h*i/3);g.lineTo(w,h*i/3)}g.stroke()}if($('#overlayHorizon')?.checked){g.strokeStyle='rgba(201,133,0,.9)';g.setLineDash([8,5]);g.beginPath();const y=horizon()*h;g.moveTo(0,y);g.lineTo(w,y);g.stroke();g.setLineDash([])}if($('#overlayDust')?.checked){g.fillStyle='rgba(220,61,91,.9)';dust().forEach(p=>{g.beginPath();g.arc(p.x*w,p.y*h,4,0,7);g.fill()})}drawRegTarget()}
function drawRegTarget(){const old=document.querySelector('.reg-search-overlay');old?.remove();if(!aircraftDetection?.bbox||!canvas?.clientWidth)return;const[bX,bY,bW,bH]=aircraftDetection.bbox,scaleX=canvas.clientWidth/canvas.width,scaleY=canvas.clientHeight/canvas.height;const el=document.createElement('div');el.className='reg-search-overlay';el.style.left=(bX*scaleX)+'px';el.style.top=(bY*scaleY)+'px';el.style.width=(bW*scaleX)+'px';el.style.height=(bH*scaleY)+'px';$('#previewWrap')?.appendChild(el)}
let zoom=1;function setZoom(z){zoom=Math.max(.5,Math.min(3,z));canvas.style.width=zoom===1?'100%':zoom*100+'%';canvas.style.height='auto';$('#zoomLabel').textContent=Math.round(zoom*100)+'%';requestAnimationFrame(drawOverlays)}
$('#zoomIn')?.addEventListener('click',()=>setZoom(zoom+.5));$('#zoomOut')?.addEventListener('click',()=>setZoom(zoom-.5));$('#zoomReset')?.addEventListener('click',()=>setZoom(1));addEventListener('resize',()=>requestAnimationFrame(drawOverlays));['overlayCenter','overlayHorizon','overlayGrid','overlayDust'].forEach(id=>$('#'+id)?.addEventListener('change',drawOverlays));
function renderTechnical(a){const items=[['Resolution',a.resolution,a.resolution==='low'?'bad':a.resolution==='borderline'?'warn':'good'],['Exposure',a.exposure,a.exposure==='good'?'good':a.exposure==='high-contrast'?'warn':'bad'],['Noise',a.noise,a.noise==='low'?'good':a.noise==='moderate'?'warn':'bad'],['Clipping',(a.clip*100).toFixed(1)+'% pixels',a.clip<.035?'good':a.clip<.07?'warn':'bad'],['Backlight',a.back.level,a.back.level==='low'?'good':a.back.level==='moderate'?'warn':'bad']];$('#checksList').innerHTML=items.map(x=>`<div class="technical-item ${x[2]}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$('#reviewSummary').textContent=`Technical review complete • ${a.score}/100 pre-screen score`;$(`#score`) .textContent=a.score;$('#scoreRing').style.background=`radial-gradient(circle,#fff 58%,transparent 59%),conic-gradient(${a.score>=80?'#079669':a.score>=60?'#c98500':'#dc3d5b'} ${a.score*3.6}deg,#dce7f1 ${a.score*3.6}deg)`;$('#verdict').textContent=a.score>=80?'Strong technical result':a.score>=60?'Review recommended':'Needs attention';$('#verdictText').textContent='Technical aid only — not an acceptance prediction.';$('#exposureNote').textContent=`Average luminance ${a.mean.toFixed(0)} • ${a.exposure}`;$('#aircraftLight').textContent=a.back.aircraft.toFixed(0);$('#frontLight').textContent=a.back.front.toFixed(0);$('#topLight').textContent=a.back.top.toFixed(0);$('#behindLight').textContent=a.back.rear.toFixed(0);$('#belowLight').textContent=a.back.bottom.toFixed(0);$('#brightestSide').textContent=a.back.brightest;$('#backlightMetric').textContent=a.back.risk+'% risk';$('#backlightNote').textContent=a.back.message;$('#lightBarFill').style.width=a.back.risk+'%';drawHistogram(a);const rec=[];if(a.resolution==='low')rec.push('Use the highest-resolution original available.');if(a.exposure!=='good')rec.push('Review exposure and clipped detail before export.');if(a.noise!=='low')rec.push('Inspect noise at 100% before export.');if(a.back.level!=='low')rec.push('Check the aircraft edges for light loss.');if(!rec.length)rec.push('Technical checks look clean. Inspect the image at 100% before submission.');$('#checklist').innerHTML=rec.map(x=>`<div class="check-item">✓ ${x}</div>`).join('')}
function aircraftState(r){['aircraftState','aircraftStateDetail'].forEach(id=>{const e=$('#'+id);if(!e)return;e.className='aircraft-state '+(r.found===true?'detected':r.found===false?'none':'');e.textContent=r.message})}
let modelPromise=null;async function detectAircraft(){if(aircraftDetection)return{found:true,message:`Aircraft detected • ${Math.round(aircraftDetection.confidence*100)}% confidence.`};if(!window.cocoSsd)return{found:null,message:'Aircraft detector unavailable.'};try{modelPromise=modelPromise||cocoSsd.load();const model=await modelPromise;const small=document.createElement('canvas'),max=1280,s=Math.min(1,max/Math.max(canvas.width,canvas.height));small.width=Math.max(1,Math.round(canvas.width*s));small.height=Math.max(1,Math.round(canvas.height*s));small.getContext('2d').drawImage(canvas,0,0,small.width,small.height);const pred=await model.detect(small,15),p=pred.filter(x=>x.class==='airplane'&&x.score>=.28).sort((a,b)=>b.score-a.score)[0];if(!p)return{found:false,message:'No aircraft detected in this image.'};const k=1/s;aircraftDetection={bbox:[p.bbox[0]*k,p.bbox[1]*k,p.bbox[2]*k,p.bbox[3]*k],confidence:p.score};return{found:true,message:`Aircraft detected • ${Math.round(p.score*100)}% confidence.`}}catch(e){console.warn(e);return{found:null,message:'Aircraft detector could not run.'}}}
function normalizeReg(s){return String(s||'').toUpperCase().replace(/[^A-Z0-9-]/g,'').replace(/^(ZS|ZU)([A-Z0-9]{3,5})$/,'$1-$2')}
function validReg(s){const r=normalizeReg(s);return /^(ZS|ZU)-[A-Z0-9]{3,5}$/.test(r)||/^[A-Z]-[A-Z0-9]{4}$/.test(r)||/^[A-Z]{2}-[A-Z0-9]{3,5}$/.test(r)||/^N[0-9]{1,5}[A-Z]{0,2}$/.test(r)||/^(JA|VH|EC|EI|PH|OO|SE|OH|9H)-[A-Z0-9]{3,5}$/.test(r)}
function candidates(text){const t=String(text||'').toUpperCase().replace(/\n/g,' '),out=[];const pats=[/\bZS[- ]?[A-Z0-9]{3,5}\b/g,/\bZU[- ]?[A-Z0-9]{3,5}\b/g,/\bN[0-9]{1,5}[A-Z]{0,2}\b/g,/\b(?:JA|VH|EC|EI|PH|OO|SE|OH|9H)[- ]?[A-Z0-9]{3,5}\b/g,/\b[A-Z]{2}[- ]?[A-Z0-9]{3,5}\b/g];for(const re of pats){for(const m of t.matchAll(re)){const r=normalizeReg(m[0]);if(validReg(r)&&!out.includes(r))out.push(r)}}return out}
function makeCrop(source,b,kind){const[bX,bY,bW,bH]=b;const c=document.createElement('canvas');let x=bX,y=bY,w=bW,h=bH;if(kind===1){x=bX+bW*.35;y=bY+bH*.15;w=bW*.65;h=bH*.7}else if(kind===2){x=bX+bW*.2;y=bY+bH*.45;w=bW*.8;h=bH*.45}const pad=Math.max(8,Math.min(source.width,source.height)*.01);x=Math.max(0,x-pad);y=Math.max(0,y-pad);w=Math.min(source.width-x,w+pad*2);h=Math.min(source.height-y,h+pad*2);const scale=Math.min(4,2200/Math.max(w,h));c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));const g=c.getContext('2d');g.imageSmoothingQuality='high';g.drawImage(source,x,y,w,h,0,0,c.width,c.height);return c}
async function getWorker(){if(!ocrWorker)ocrWorker=await Tesseract.createWorker('eng');return ocrWorker}
async function readCrop(c,run,label){if(regCancelled||run!==regRun)return[];regProgress(Math.min(88,35+runProgressStep),label);const worker=await getWorker();if(regCancelled||run!==regRun)return[];const r=await worker.recognize(c);return candidates(r.data.text)}let runProgressStep=0;
async function detectRegistration(){const run=++regRun;regCancelled=false;detectedReg='';regProgress(2,'Waiting for aircraft area…');$('#registrationPill').textContent='RUNNING';$('#registrationValue').textContent='Reading…';$('#registrationStatus').innerHTML='<span class="ocr-status"><span class="spinner"></span>Searching the aircraft for its registration…</span>';$('#cancelRegistrationBtn').disabled=false;if(!aircraftDetection){regCancelled=true;return}const target=document.querySelector('.reg-target');if(target)target.innerHTML='<b>REG SEARCH AREA</b><strong>Focused on the detected aircraft • OCR will scan the fuselage area first.</strong>';const source=imageCanvas();const all=[];for(let k=0;k<3;k++){if(regCancelled||run!==regRun)return;runProgressStep=18+k*23;const c=makeCrop(source,aircraftDetection.bbox,k);const got=await readCrop(c,run,k===0?'Reading aircraft markings…':k===1?'Reading rear/side fuselage…':'Reading lower fuselage…');got.forEach(x=>{if(!all.includes(x))all.push(x)});if(all.length){setRegistration(all[0]);regProgress(100,'Registration found');$('#registrationPill').textContent='FOUND';return}}if(regCancelled||run!==regRun)return;regProgress(100,'No clear registration found');$('#registrationPill').textContent='NOT FOUND';$('#registrationValue').textContent='Not found';$('#registrationStatus').textContent='No confident registration was read. You can enter it manually.'}
function imageCanvas(){const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;c.getContext('2d').drawImage(canvas,0,0);return c}
function setRegistration(s){const r=normalizeReg(s);if(!validReg(r))return;detectedReg=r;$('#registrationValue').textContent=r;$('#manualReg').value=r;$('#registrationStatus').textContent='Registration candidate found. Checking JetPhotos and Planespotters…';$('#jetPhotosBtn').disabled=false;$('#planespottersBtn').disabled=false;loadSources(r)}
function sourceUrls(r){return{jet:`https://www.jetphotos.com/registration/${encodeURIComponent(r)}`,planes:`https://www.planespotters.net/search?q=${encodeURIComponent(r)}`}}
async function fetchSource(url){try{const r=await fetch('https://r.jina.ai/'+url,{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.text()}catch(e){return''}}
function parseSource(text,reg){const t=String(text||'');const clean=s=>s.replace(/\\s+/g,' ').trim();const fields=[];const wanted=['Airline','Aircraft','Serial','Serial #','Delivery date','Age','Engine model','Status','SELCAL','F/N','Comments','Aircraft Type'];for(const key of wanted){const re=new RegExp(key+'\\s*[:|]?\\s*([^\\n]{2,100})','i');const m=t.match(re);if(m&&!/JetPhotos|Planespotters|registration/i.test(m[1]))fields.push([key,clean(m[1])])}if(!fields.length){const lines=t.split(/\\n+/).map(x=>clean(x)).filter(Boolean);for(const line of lines){if(/airbus|boeing|cessna|embraer|bombardier|de havilland|piper|beechcraft|atr |learjet|gulfstream/i.test(line)&&line.length<140)fields.push(['Aircraft',line])}}return fields.slice(0,10)}
async function loadSources(reg){const box=$('#aircraftDetails');box?.classList.remove('hidden');$('#aircraftRegOut').textContent=reg;$('#aircraftSource').textContent='JetPhotos + Planespotters only';$('#jetDataStatus').innerHTML='<span class="source-dot wait"></span>Reading';$('#planespottersDataStatus').innerHTML='<span class="source-dot wait"></span>Reading';const u=sourceUrls(reg);const [j,p]=await Promise.all([fetchSource(u.jet),fetchSource(u.planes)]);const jf=parseSource(j,reg),pf=parseSource(p,reg);$('#jetDataStatus').innerHTML=`<span class="source-dot ${jf.length?'ok':'no'}"></span>${jf.length?'Data found':'No data returned'}`;$('#planespottersDataStatus').innerHTML=`<span class="source-dot ${pf.length?'ok':'no'}"></span>${pf.length?'Data found':'No data returned'}`;const merged=[...jf.map(x=>['JetPhotos',...x]),...pf.map(x=>['Planespotters',...x])];$('#aircraftFields').innerHTML=merged.length?merged.map(x=>`<div class="source-box"><h4>${x[0]}</h4><div><span>${x[1]}</span><b>${x[2]}</b></div></div>`).join(''):'<div class="source-box">No aircraft details were returned from the two requested databases.</div>';$('#aircraftSource').textContent=merged.length?[...new Set(merged.map(x=>x[0]))].join(' + '):'No data returned';$('#registrationStatus').textContent=merged.length?'Aircraft data returned from JetPhotos/Planespotters.':'Registration read, but neither database returned usable details.'}
function cancelRegistration(){regCancelled=true;regRun++;$('#registrationPill').textContent='CANCELLED';$('#registrationValue').textContent=detectedReg||'—';$('#registrationStatus').textContent='Registration reading cancelled. Technical review remains available.';regProgress(0,'Cancelled');$('#cancelRegistrationBtn').disabled=true}
$('#cancelRegistrationBtn')?.addEventListener('click',cancelRegistration);$('#retryRegistrationBtn')?.addEventListener('click',()=>{if(aircraftDetection)detectRegistration()});$('#manualRegBtn')?.addEventListener('click',()=>{const r=normalizeReg($('#manualReg').value);if(validReg(r))setRegistration(r);else $('#registrationStatus').textContent='That does not look like a supported aircraft registration.'});$('#jetPhotosBtn')?.addEventListener('click',()=>detectedReg&&window.open(sourceUrls(detectedReg).jet,'_blank','noopener'));$('#planespottersBtn')?.addEventListener('click',()=>detectedReg&&window.open(sourceUrls(detectedReg).planes,'_blank','noopener'));
$('#histExplainBtn')?.addEventListener('click',()=>{const a=$('#histogramAreas'),h=$('#histogramHelp');a?.classList.toggle('hidden');h?.classList.toggle('hidden');$('#histExplainBtn').textContent=a?.classList.contains('hidden')?'Show areas':'Hide areas'});
function technicalOnly(){if(!imgData)return;progress(10,'Rechecking image');const a=analyse(imgData,aircraftDetection?.bbox||null);lastAnalysis=a;progress(70,'Updating technical review');renderTechnical(a);progress(100,'Technical review updated');requestAnimationFrame(drawOverlays)}
async function startAnalysis(){if(!imgData)return;progress(5,'Preparing image');aircraftState({found:null,message:'Detecting aircraft…'});const det=await detectAircraft();aircraftState(det);if(det.found===false){regCancelled=true;regRun++;$('#registrationPill').textContent='STOPPED';$('#registrationValue').textContent='—';$('#registrationStatus').textContent='No aircraft detected — registration reading stopped.';$('#cancelRegistrationBtn').disabled=true;progress(48,'No aircraft found');const a=analyse(imgData,null);lastAnalysis=a;renderTechnical(a);progress(100,'Technical review complete');$('#continueWrap')?.classList.remove('hidden');requestAnimationFrame(drawOverlays);return}if(det.found===null){regCancelled=true;regRun++;$('#registrationPill').textContent='STOPPED';$('#registrationStatus').textContent='Aircraft detection unavailable — registration reading stopped.'}const techPromise=(async()=>{progress(35,'Running technical checks');const a=analyse(imgData,aircraftDetection?.bbox||null);lastAnalysis=a;renderTechnical(a);progress(75,'Finalising technical review');})();const regPromise=det.found===true?detectRegistration():Promise.resolve();await techPromise;progress(100,'Technical review complete');$('#continueWrap')?.classList.remove('hidden');requestAnimationFrame(drawOverlays);await regPromise}
window.startAnalysis=startAnalysis;window.updateResize=window.updateResize||function(){};
$('#analyzeBtn')?.addEventListener('click',e=>{e.preventDefault();technicalOnly()});
const target=document.createElement('div');target.className='reg-target';target.innerHTML='<b>REG SEARCH AREA</b><strong>Waiting for aircraft detection…</strong>';$('#registrationStatus')?.after(target);
})();